### PR TITLE
Add flake.nix dev env

### PR DESCRIPTION
**Pull request by elsirion**
Defines a reproducible dev environment in nix that should contain all the necessary dependencies (at least it worked for me).

### CODE REVIEW

**Comment by sectore** [comment]
@elsirion Great, thx :+1: 

Seems another `sha256` is needed for Rust `nightly` - any idea? 

```bash
nix develop
[...]
error: hash mismatch in fixed-output derivation '/nix/store/h9dp7vkn7hjndfcmnghlarz6mn5sg8y2-channel-rust-nightly.toml.drv':
         specified: sha256-Fe5JnQedOkiX4lQt5UN0zkbiIOtqe0u1sxFJxY+qnU4=
            got:    sha256-HNVHjhD3Dy7Dj4NwsJZM44AlwBx9j95jRiNdMyVOYOw=
```

Using `sha256-HNVHjhD3Dy7Dj4NwsJZM44AlwBx9j95jRiNdMyVOYOw=` works fine for me, but not sure if another hash might break anything on other machines...? 

What's your output of the following? (_I'm using `sha256-HNVHjhD3Dy7Dj4NwsJZM44AlwBx9j95jRiNdMyVOYOw=` here_)
```bash
nix develop

rustc --version
rustc 1.72.0-nightly (22e9fe644 2023-06-23)
```

**[UPDATE]** _I'm not a `Nix` expert,_ but it seems in `flake.nix` `pkgs = import nixpkgs { inherit system; };` targets the OS running on users machines. And `nix store` is fetching Rust binaries from `https://static.rust-lang.org/dist/2023-06-24/channel-rust-nightly.toml`, where different binaries for different OS are listed, which will end in different `sha256` hashes, at least as long as users run different OS (I'm on Ubuntu 22.04).

**Comment by elsirion** [comment]
I'm getting `rustc 1.72.0-nightly (04075b320 2023-06-22)`, so maybe when I first ran it the date "2023-06-24" defaulted to some older version (can happen if builds fail iirc, it just takes the last successful one).

**Comment by elsirion** [comment]
I updated the hash, it likely kept working for me due to caching. Now I'm getting `rustc 1.72.0-nightly (22e9fe644 2023-06-23)` too.

**Comment by elsirion** [comment]
The `pkgs = import nixpkgs { inherit system; };` is also relevant, but won't lead to this error, but rather to `flake.lock` changing when it shouldn't. I'll fix later.

**Comment by elsirion** [comment]
> The `pkgs = import nixpkgs { inherit system; };` is also relevant, but won't lead to this error, but rather to `flake.lock` changing when it shouldn't. I'll fix later.

False alarm: the `system` referenced here is bound earlier as the input to the lambda given to `flake-utils.lib.eachDefaultSystem`. I just got confused because one can use the system's default nixpkgs afaik, but here we already specify the url in `inputs`:

https://github.com/sectore/fm-faucet-leptos/blob/3eeb69e0275ae467275eb16531b2a2659986cb89/flake.nix#L3

**Pull request merged**
